SEED_USERS = [
    {
        "email": "linyu@pingo.local",
        "name": "momo",
        "school": "清华大学",
        "grade": "研二",
        "city": "上海",
        "role": "多模态算法实习生",
        "skills": "多模态评测、数据清洗、模型微调",
        "wants": "AI 营销产品的业务链路与保险行业落地",
        "tags": ["VLM", "AI", "求职交流", "ToB"],
        "intro": "在做 ToB 多模态模型评测与微调，想找能交换业务落地经验的搭子。",
        "letter": "M",
        "tone": "blue",
        "referral_code": "PINGO-LINY",
    },
    {
        "email": "chenmo@pingo.local",
        "name": "小陈同学",
        "school": "北京大学",
        "grade": "研一",
        "city": "北京",
        "role": "AI 产品实习生",
        "skills": "客户访谈、需求拆解、AI 产品落地",
        "wants": "模型能力边界和工程交付流程",
        "tags": ["产品", "AI", "ToB"],
        "intro": "从客户访谈拆需求，想补上模型能力和工程交付。",
        "letter": "陈",
        "tone": "coral",
        "referral_code": "PINGO-CHEN",
    },
    {
        "email": "zhouye@pingo.local",
        "name": "一一",
        "school": "浙江大学",
        "grade": "大四",
        "city": "杭州",
        "role": "推荐算法实习生",
        "skills": "召回排序、特征工程、离线评测",
        "wants": "多模态理解与 ToB 数据闭环",
        "tags": ["AI", "推荐", "搜推"],
        "intro": "做内容推荐与特征工程，想交换多模态和 ToB 数据经验。",
        "letter": "一",
        "tone": "violet",
        "referral_code": "PINGO-ZHOU",
    },
    {
        "email": "xuyuan@pingo.local",
        "name": "小林",
        "school": "上海交通大学",
        "grade": "研一",
        "city": "上海",
        "role": "Agent 全栈实习生",
        "skills": "Agent 工作流、RAG、前后端工程",
        "wants": "模型评测方法和产品化取舍",
        "tags": ["开发", "AI", "Agent"],
        "intro": "搭 Agent 工作流和 RAG，想找产品和算法一起把链路跑通。",
        "letter": "林",
        "tone": "green",
        "referral_code": "PINGO-XUYU",
    },
    {
        "email": "tangli@pingo.local",
        "name": "七喜",
        "school": "复旦大学",
        "grade": "大三",
        "city": "上海",
        "role": "用户增长实习生",
        "skills": "用户增长、内容裂变、出海投放",
        "wants": "AI 产品如何讲清楚价值和转化",
        "tags": ["增长", "产品", "出海"],
        "intro": "做增长和出海投放，想和做 AI 产品的人交换叙事。",
        "letter": "7",
        "tone": "yellow",
        "referral_code": "PINGO-TANG",
    },
    {
        "email": "gucheng@pingo.local",
        "name": "张同学",
        "school": "哈尔滨工业大学",
        "grade": "研二",
        "city": "哈尔滨",
        "role": "工业软件开发实习生",
        "skills": "C++、工业软件、性能优化",
        "wants": "AI 能力如何嵌进已有工程系统",
        "tags": ["开发", "工业软件"],
        "intro": "做工业软件性能，想了解 AI 能力怎么嵌进现有系统。",
        "letter": "张",
        "tone": "gray",
        "referral_code": "PINGO-GUCH",
    },
    {
        "email": "jianghe@pingo.local",
        "name": "阿北",
        "school": "中国科学技术大学",
        "grade": "大四",
        "city": "合肥",
        "role": "模型安全实习生",
        "skills": "模型安全、红队测试、攻防评估",
        "wants": "真实业务里的模型上线与评测流程",
        "tags": ["AI", "安全", "红队"],
        "intro": "做模型安全和红队，想看真实业务怎么上线评测。",
        "letter": "北",
        "tone": "red",
        "referral_code": "PINGO-JIAN",
    },
    {
        "email": "suli@pingo.local",
        "name": "小雨",
        "school": "南京大学",
        "grade": "大三",
        "city": "南京",
        "role": "商业化产品实习生",
        "skills": "商业化策略、数据分析、增长实验",
        "wants": "AI 功能如何定价和讲给客户",
        "tags": ["产品", "增长", "商业化"],
        "intro": "做商业化和增长实验，想交换 AI 功能怎么卖。",
        "letter": "雨",
        "tone": "pink",
        "referral_code": "PINGO-SULI",
    },
    {
        "email": "chengyi@pingo.local",
        "name": "cc",
        "school": "华中科技大学",
        "grade": "研一",
        "city": "武汉",
        "role": "具身智能实习生",
        "skills": "VLA、机器人数据、具身智能评测",
        "wants": "多模态模型在业务侧的微调经验",
        "tags": ["AI", "VLA", "具身智能"],
        "intro": "做 VLA 和机器人数据，想交换多模态微调经验。",
        "letter": "C",
        "tone": "cyan",
        "referral_code": "PINGO-CHYI",
    },
    {
        "email": "wenxi@pingo.local",
        "name": "王晓宁",
        "school": "武汉大学",
        "grade": "大四",
        "city": "武汉",
        "role": "求职交流 / 产品实习",
        "skills": "面试复盘、案例分析、求职规划",
        "wants": "算法和产品实习的真实工作流",
        "tags": ["求职交流", "产品"],
        "intro": "整理面试复盘和求职规划，想换真实项目工作流。",
        "letter": "王",
        "tone": "orange",
        "referral_code": "PINGO-WENX",
    },
]
